# Generated by Django 3.0.7 on 2020-06-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('img_url', models.TextField(max_length=100)),
                ('article_url', models.TextField(max_length=100)),
                ('timestamp', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Police_victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_buffer', models.TextField(default='-', max_length=20, verbose_name='error')),
                ('date', models.TextField(default='yyyy.mm.dd', max_length=20, verbose_name='날짜')),
                ('name', models.TextField(default='default_name', max_length=50, verbose_name='이름')),
                ('state', models.TextField(default='default_state', max_length=10, verbose_name='주(State)')),
                ('cause_of_death', models.TextField(default='default_manner_of_death', max_length=50, verbose_name='사인')),
            ],
        ),
        migrations.CreateModel(
            name='Victims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.TextField(max_length=10)),
                ('gender', models.TextField(max_length=10)),
                ('race', models.TextField(max_length=30)),
                ('date', models.TextField(max_length=20)),
                ('state', models.TextField(max_length=10)),
                ('cause_of_death', models.TextField(max_length=50)),
                ('mental_illness', models.TextField(max_length=20)),
                ('unarmed', models.TextField(max_length=20)),
                ('alleged_weapon', models.TextField(max_length=30)),
                ('alleged_threat_level', models.TextField(max_length=20)),
                ('fleeing', models.TextField(max_length=20)),
            ],
        ),
    ]
